# Generated by Django 5.1.4 on 2024-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
