# Generated by Django 5.1.4 on 2024-12-10 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_categoria_cliente_fornecedor_produto_vendas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fornecedor",
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.AlterModelOptions(
            name="vendas",
            options={"verbose_name": "Venda", "verbose_name_plural": "Vendas"},
        ),
    ]
