# Generated by Django 5.1.4 on 2025-01-08 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_fornecedor_options_alter_vendas_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fornecedor",
            old_name="empresa",
            new_name="company",
        ),
    ]
