# Generated by Django 5.1.4 on 2025-01-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_rename_empresa_fornecedor_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.cliente",
                verbose_name="cliente",
            ),
        ),
    ]
