# Generated by Django 5.1.4 on 2025-01-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_vendas_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendas",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="vendas",
            name="quantity",
        ),
        migrations.CreateModel(
            name="VendaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.produto"
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.vendas"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vendas",
            name="produtos",
            field=models.ManyToManyField(
                through="users.VendaProduto",
                to="users.produto",
                verbose_name="produtos",
            ),
        ),
    ]
