# Generated by Django 5.1.4 on 2025-01-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_vendas_produto_remove_vendas_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendas",
            name="produtos",
        ),
        migrations.AddField(
            model_name="vendas",
            name="produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.produto",
                verbose_name="produto",
            ),
        ),
        migrations.AddField(
            model_name="vendas",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="VendaProduto",
        ),
    ]
