# Generated by Django 5.1.4 on 2025-02-01 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_vendas_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
                verbose_name="CPF",
            ),
        ),
    ]
