# Generated by Django 5.1.4 on 2025-02-03 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_produto_categoria_alter_produto_fornecedor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="quantity",
            ),
        ),
    ]
