# Generated by Django 5.1.4 on 2025-02-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_categoria_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="description",
            field=models.TextField(max_length=115, verbose_name="description"),
        ),
    ]
