# Generated by Django 5.1.4 on 2025-02-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_categoria_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="description",
        ),
        migrations.AlterField(
            model_name="categoria",
            name="name",
            field=models.CharField(max_length=40, verbose_name="name"),
        ),
    ]
