# Generated by Django 5.1.4 on 2025-02-20 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_fornecedor_description_alter_categoria_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="users.categoria",
                verbose_name="Categoria",
            ),
        ),
    ]
