# Generated by Django 5.1.4 on 2025-02-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_vendas_cpf_cliente_vendas_telefone_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="total"
            ),
        ),
    ]
