# Generated by Django 5.1.4 on 2025-02-22 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_remove_cliente_cep_cliente_complemento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato inválido de CPF. Use: 000.000.000-00",
                        regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="neighborhood",
            field=models.CharField(max_length=100, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O número deve conter apenas dígitos.", regex="^\\d+$"
                    )
                ],
                verbose_name="Número",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato inválido de telefone. Ex: (11) 91234-5678",
                        regex="^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$",
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Rua"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="uf",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
                verbose_name="UF",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="cpf_cliente",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF deve conter apenas números.", regex="^\\d{11}$"
                    )
                ],
                verbose_name="cpf",
            ),
        ),
    ]
