# Generated by Django 5.1.4 on 2025-02-22 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_cliente_city_alter_cliente_complemento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF deve conter apenas números.", regex="^\\d{11}$"
                    )
                ],
                verbose_name="cpf",
            ),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="cpf_cliente",
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O CPF deve estar no formato XXX.XXX.XXX-XX.",
                        regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                    )
                ],
                verbose_name="CPF do Cliente",
            ),
        ),
    ]
