# Generated by Django 5.1.4 on 2025-02-24 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_cliente_cpf_alter_vendas_cpf_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
                verbose_name="CPF",
            ),
        ),
    ]
