# Generated by Django 5.1.4 on 2025-02-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_alter_vendas_cliente_alter_vendas_produto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.fornecedor",
                verbose_name="Fornecedor",
            ),
        ),
    ]
