# Generated by Django 5.1.4 on 2025-02-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_alter_produto_fornecedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.fornecedor",
                verbose_name="Fornecedor",
            ),
        ),
    ]
