# Generated by Django 5.1.4 on 2025-02-24 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_alter_fornecedor_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="telefone_cliente",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O telefone deve estar no formato (XX) XXXXX-XXXX.",
                        regex="^\\(\\d{2}\\) \\d{5}-\\d{4}$",
                    )
                ],
                verbose_name="Telefone do Cliente",
            ),
        ),
    ]
